### ISSUE TITLE
?ergm-terms behavior

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#138]
When typing `?ergm-terms` in the console, tab completion shows it is available

![image](https://user-images.githubusercontent.com/8194530/74456787-34db1a00-4e3c-11ea-81f4-ac0c14938bca.png)

But execution gives:
```
> ?ergm-terms
Error in .helpForCall(topicExpr, parent.frame()) : 
  no documentation for function ‘-’ and signature ‘e1 = "function", e2 = "function"’
In addition: Warning message:
In .helpForCall(topicExpr, parent.frame()) :
  no method defined for function ‘-’ and signature ‘e1 = "function", e2 = "function"’
```
This seems inconsistent.

**Comment by sgoodreau** [comment]
You have to put it in quotes:

?"ergm-terms"

It's an unfortunate consequence of the decision to use a dash in the name.  Without the quotes it parses it as a minus symbol between two separate objects (hence the error "no documentation for function ‘-’"). It's always been this way, and definitely trips people up now and again. 

AFAIK, the only solution is to change the name.  Perhaps with an alias, so old tutorials don't break. Not sure if it's worth it though.

**Comment by martinamorris** [comment]
@sgoodreau i'm aware -- just saying that there's an inconsistency here, since tab-completion recognizes the argument without the quotes

**Comment by mbojan** [comment]
It is also aliased with a dot, so `?ergm.terms` should work.

**Comment by mbojan** [comment]
... but indeed the page name with a minus is unfortunate because it is not a valid R symbol, hence quoting is necessary.

**Comment by martinamorris** [comment]
@mbojan does that mean we should consider renaming the page to `ergm.terms`?

**Comment by mbojan** [comment]
@martinamorris I just tried that and it seems to work OK for me in RStudio. When I start typing `?ergm-` the code completion pop up, when I scroll down to `ergm-terms` and press Tab it completes it correctly with back-quotes `` ?`ergm-terms` ``. 

The reality is actually a bit involved and funny because in fact you can name pages with a minus (I was wrong here https://github.com/statnet/ergm/issues/138#issuecomment-585914632 ) but it is handled specially: the first word is interpreted as a "topic", the second as "type". Example: most packages have a package-level man page with a `\name` of the form `packagename-package`, so there is `stats-package`, `network-package` and in fact `ergm-package`. You can also have `classname-class` to document a class (and some types). The convention is to name the pages `topic-type.Rd`. You can open those with `package?ergm` or `package?stats` because `?` is in fact an operator with left- and right-hand side arguments. The LHS is the "type", see also `?"?"`. The side effect of this convention is that you can also use `terms?ergm` to get to the terms help page 😄

**Comment by krivit** [comment]
@mbojan This is fascinating.

**Comment by martinamorris** [comment]
I need the exploding head emoji here.

@mbojan thx for the deep dive.  are we agreed then to make the change to "ergm.terms"?

**Comment by mbojan** [comment]
@martinamorris I think changing the name to `ergm.terms` and keeping `ergm-terms` as an alias should not have any negative side effects.

**Comment by krivit** [comment]
On further thought, maybe we should go all-in on this?

We rename `ergm`'s `ergm-terms` to `ergm-ergmTerm`, then `ergm.count`'s terms `ergm.count-ergmTerm`, etc.; then teach the users to type, say, `ergmTerm?PKG` to get the list of and the help for the terms in package `PKG`.

Similarly with `ergm-ergmConstraint`, `ergm-ergmProposal`, `ergm-ergmReference`, etc..

**Comment by martinamorris** [comment]
the inelegance of repeating "ergm" so many times makes me cringe a bit.  is it possible to remove the leading "ergm" from the component after the dash?

**Comment by krivit** [comment]
Thinking about it some more (and I should have probably started with this), it would make sense for the term list to also alias `ergmTerm` itself, so that `?ergmTerm` gives the user a choice of which package's terms they want to look up.

Similarly, it would alias `ergmTerm` would also alias `edges-ergmTerm` and `ergmConstraint` would alias `edges-ergmConstraint`, so that, `ergmTerm?edges` and `ergmConstraint?edges` would lead to their respective help files.

**Comment by krivit** [comment]
> the inelegance of repeating "ergm" so many times makes me cringe a bit. is it possible to remove the leading "ergm" from the component after the dash?

In light of the discussion at https://github.com/statnet/ergm/issues/28, we shouldn't need to have a package-specific term index, since `ergm` alone can update its own index in real time.

So, `?ergmTerm` need only be defined in `ergm`, and `ergm-ergmTerm` etc. shouldn't be needed.

**Comment by krivit** [comment]
Obviated by #28 being actioned.
