### ISSUE TITLE
Are MCMC diagnostic plots reversed?

### ISSUE THREAD

**Issue by sgoodreau** [statnet/ergm#163]
We're in the middle of running the NME workshop, and hit something that surprised us.  Namely:
```
library(ergm)
data(florentine)
summary(flomarriage~edges+triangle)
fit <- ergm(flomarriage~edges+triangle)
mcmc.diagnostics(fit)
```
This yields the following plot:
![image](https://user-images.githubusercontent.com/8250754/90543997-55619500-e13b-11ea-83a8-fd67599cf34e.png)

Looking at triangles, the observed value is 3 triangles.  And, at least given how we've all always assumed the plots work, the simulated values during the fit go well below three *less* than the observed values, but never go more than three *above* the observed values. It of course must be the opposite of this.  Has this plot always behaved this way and we're just interpreting it backwards from what it's meant to represent, or did it somehow accidentally get reversed somewhere along the way?  

This is all with ergm 3.10.4.

**Comment by krivit** [comment]
This is the technically correct behaviour. Recall that (ignoring curved models, for a second), the estimating function (the gadient of the log-likelihood, the score) is <img src="https://render.githubusercontent.com/render/math?math=l'(\theta) = g(y)-\mu(\theta)">. In MCMC-based methods, we replace <img src="https://render.githubusercontent.com/render/math?math=\mu(\theta)"> with a simulated estimate. Thus, in the simulated estimating function values, the MCMC sampled statistics replace the <img src="https://render.githubusercontent.com/render/math?math=\mu(\theta)">, not the observed sufficient statistic value <img src="https://render.githubusercontent.com/render/math?math=g(\theta)">, which is fixed during the estimation. That's why we subtract the simulated from the observed and not the other way around. (Think of simulated > observed as being not "our parameter guess is too high" but "our next parameter guess should be lower", since that's what the gradient is for.)

However, there is no law that says that we are obligated to plot the estimating function rather than its negation for diagnostic purposes. If it makes more intuitive sense the other way, we can change it.

**Comment by sgoodreau** [comment]
Thanks @chad-klumb and @krivit. From the perspective of the user interpreting the diagnostics, I think the old behavior is much better, since the entities on the graph match the two pieces they are most directly thinking about (the expected value of the statistic, which is fixed, and the simulated values of the statistic, which are varying).

**Comment by krivit** [comment]
Thanks, @sgoodreau . Anyone else have any thoughts? It's a pretty straightforward change.

**Comment by martinamorris** [comment]
I agree with Steve.  It's more intuitive to have the y-axis interpretation be that the simulation produces "too many" and "too few"  triangles.  

That's the reverse of the usual ordering for statistics of the sort "observed - expected", so it may end up being confusing for other folks who have that in mind.  

So if it is possible to add some clarifying text to the y-axis, like "sim - target", and a clear statement in the man page that we are reversing the estimating function, that would be good.

**Comment by krivit** [comment]
OK. Do we want to do this for MCMC diagnostics plots only, or runtime traceplots as well?

**Comment by martinamorris** [comment]
Should be consistent in both, yes?
