### ISSUE TITLE
ergm 3.11.0 - "NAs cause error in term ‘nodematch’ " problem

### ISSUE THREAD

**Issue by hhekim** [statnet/ergm#190]
Hi,
I don't know if this page is a suitable place for this but here is my issue:
I am getting error after upgrading to **ergm 3.11.0**
I have a network object _friends_ which has two vertex attributes _alliance_ and _ideology_ among others. Attribute _alliance_ has NAs for some nodes because those nodes are not part of any alliance.
I was running **ergm** with following code perfectly well before the upgrade:
`m3 <- ergm(friends~edges + nodematch("alliance",diff=F) + nodematch("ideology",diff=F))`
However, now I am getting following error:
`Error: In term ‘nodematch’ in package ‘ergm’: Attribute ‘"alliance"’ has missing data, which is not currently supported by ergm.`
How can I make **ergm** accept data with NAs? What should I do?

Thanks,
Hakan

**Comment by mbojan** [comment]
Hello @hhekim , since this is not a software problem per se, an email to statnet_help mailing list or a question on Stackoverflow with a "statnet" or "ergm" tags would be preferable...

Throwing away the data is a bad thing and throwing away network data is even worse, so removing nodes for which `alliance` is `NA` is not advised. If the number of nodes with `NA` on `alliance` is small you might considering adding them to one of the existing categories (such as "other" if there is one). If the number is substantial you may try recoding the `NA`s into a valid value and treat it as a separate category. Then, looking at mixing matrix might tell you with whom those nodes are often connected. Depending on the availability of the data you might also consider (multiple-) imputing the missing values using the remaining observed attributes.

See also https://stackoverflow.com/questions/35854478/can-the-ergm-statnet-package-deal-with-missing-attribute-data/36327831#36327831 which was about continuous node attributes.

**Comment by krivit** [comment]
@hhekim , thanks the repot, and @mbojan , thanks for addressing it.

As @mbojan points out, this is not really a bug: ERGM specification doesn't really accommodate missing attributes. There are extensions that do (or try to), but none of them are implemented in the package at this time.

**Comment by hhekim** [comment]
Thanks @mbojan and @CarterButts for your comments.
As you indicated, I was trying to use NA as a value which was wrong. I redefined the _alliance_ to cover every observations.
Thanks again.

HHekim
