### ISSUE TITLE
Maineffects command

### ISSUE THREAD

**Issue by QQloveddme** [statnet/ergm#192]
Hi，I'm wondering the data package"lhds", which is used in the book "An introduction to ERGMs" (Dr. Harris) occurs some bugs. When I came to the command 19 about maineffects,the R just told me' **In term ‘nodefactor’ in package ‘ergm’: Attribute ‘"years"’ has missing data, which is not currently supported by ergm**.' and I cannot carry on my study. I checked the attribute"years" and found 27 N/A, Although I assign them certain values, R still showed the same bug. Dose anyone know what happened to this data package and how I can solve this problem? Thanks.

**Comment by mbojan** [comment]
Hi @QQloveddme , since the 'ergmharris' package in which the `lhds` can be found is not part of Statnet there is little we can do to fix potential problems you find in these data. You should contact Jenine Harris, the author of the 'ergmharris' package, with any problems with the data.

In general, `ergm()` does not allow `NA`s on vertex attributes. This is not a bug in Statnet. To proceed you need to either remove the nodes with missing data (not recommended) or replace the `NA`s with some valid values and adjust your model specifications accordingly.

**Comment by QQloveddme** [comment]
Thank you for your reply! I will try to email her.
