### ISSUE TITLE
summary.ergm reports "Monte Carlo MLE Results" for some dyad-independent models

### ISSUE THREAD

**Issue by drh20drh20** [statnet/ergm#196]
Reproducible example:

data(faux.mesa.high)
summary(ergm(faux.mesa.high~nodecov(~cbind(Grade,Grade^2))))

**Comment by krivit** [comment]
Moved to public, since it affects all versions.

In this case, we can probably modify `print.summary.ergm()` to print more accurate output. (It's probably not a good idea to remove the MCMC% column from the coefficients table, however, since it makes things less predictable for any downstream functions.)

**Comment by mbojan** [comment]
I think it is primarily the text above the coef table that is misleading.

**Comment by krivit** [comment]
OK, this is probably a one-line fix.

**Comment by krivit** [comment]
The framework in `dev` makes it a much simpler fix, so I am fixing it there.
