### ISSUE TITLE
R CMD check notes and errors

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm#233]
CI fails on Windows and passes with notes/warnings on other systems:

- [ ] vignette problems: no files in `inst/docs` and `VignetteBuilder`-related message
- [ ] `License` entry in DESCRIPTION: complains about the additional file
- [x] On Windows only: package Rmpi not available (strange)?

**Comment by krivit** [comment]
* The `inst/docs` issue is because we are saving runtime by not building vignettes before running the check. Perhaps after the Great Merge, when GitHub private action minutes are less scarce, we can enable that.
* Unless I am misreading something, the License thing has always been there. We have a separate file `LICENSE`, as per the specification.
* Not much we can do about Windows other than remove `Rmpi` from Suggests and not test that code. Otherwise, all we can do its wait for `Rmpi` 0.6-9.1 to get built for the other versions of Windows. (It's been a week; let's give it another day or two at least.)

**Comment by mbojan** [comment]
> - Unless I am misreading something, the License thing has always been there. We have a separate file `LICENSE`, as per the specification.

I'm familiar the `[license] + file LICENSE` specification (common with MIT license), but I've never seen that R CMD check message. Perhaps they do not expect the additional file with GPL?


> - Not much we can do about Windows other than remove `Rmpi` from Suggests and not test that code. Otherwise, all we can do its wait for `Rmpi` 0.6-9.1 to get built for the other versions of Windows. (It's been a week; let's give it another day or two at least.)

That would be very strange, but perhaps let's just wait and see.

**Comment by krivit** [comment]
Looks like the Rmpi thing has fixed itself.

**Comment by mbojan** [comment]
Yay! ;)

**Comment by krivit** [comment]
Large components issue will go away once we chop the ad hoc bit at the end off and submit to CRAN.

**Comment by mbojan** [comment]
Now it is all green (with Notes). We can close this if you want, unless you'd rather have a reminder...

**Comment by krivit** [comment]
Yeah, let's close, since the rest of it is in the regular release checklists.
