### ISSUE TITLE
Deprecate or excise "trustregion"?

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#293]
To avert potential confusion, this ticket is *not* about the `trust()` algorithm used to maximise the estimated likelihood when it doesn't have a closed form.

This is about the `*.trustregion` control options that cap the amount by which the estimated log-likelihood is allowed to increase during a given iteration. It's found in the original commit of the package to SVN in 2007.

I've floated the idea of removing it for a while, and I'd like to go ahead and do it. My reasons:
1. It makes assumptions about the magnitudes of likelihood changes, which can be wrong for large networks and valued ERGMs.
2. The Hummel step length algorithm does what it does, but better.
3. I don't think I've actually ever seen an `ergm()` run hit the trustregion cap and then recover and proceed to converge. Invariably, it just hits it again and again before failing for some other reason.
4. As far as I can tell, all Statnet Project vignettes, workshops, and documentation only ever mentions it in order to tell the user to disable it. Other users only mention it when they copy-paste our example code.
5. It significantly complicates the code in many places.

@drh20drh20 , @handcock , @CarterButts , what do you think? It's (one of) your creations.

More broadly, is anyone actually using this capability?

**Comment by CarterButts** [comment]
This is a good question.  My vague memory is that it was useful early on, in the pre-Hummel era.  It seems to me like it _should_ still be useful,* but I don't know if it _is_.  (As you say, my practical experience is that most models are either too strained to work, or work pretty well with some minimal tinkering.)  It would probably be helpful to create a toy example of a model that is just barely estimable, and see if turning off trustregion ever matters.  I suppose I would support trying to keep it as an option (perhaps only used in the binary case) if it can be shown to matter, but otherwise it may be better to let it go.

* Indeed, I like the observation that Hummel stepping actually is a trust region method, but implemented in the mean value space.  So perhaps we should ask ourselves whether there is a setting in which we would want to estimate our step length with respect to a likelihood-based metric instead.  For Geyer-Thompson, I tend to think not, but there may be some case that I'm not thinking of.....

**Comment by CarterButts** [comment]
(To clarify, the bullet in the above goes with the asterisk.  Markdown struck unexpectedly.)

**Comment by handcock** [comment]
I think we should remove it. The  original idea was a "cap", much like for the edge count, to allow gross control. Simplifying the code is always a good idea. While there may be cases where it helps they are likely few. Finally, improvements for this class of problems can be looked for using the tapering ideas in computation, which I have found dramatically improve model and computational stability

**Comment by drh20drh20** [comment]
I'm fine with excising it; it's hard for me to see a reason to keep it, absent some kind of theory that provides better guidance on how to choose it than "try 20" :)

**Comment by krivit** [comment]
'Tis done.
