### ISSUE TITLE
offset statistic names with curved terms inside operator terms

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#320]
This doesn't seem to behave as I would expect, e.g.

```
require(ergm)
nw <- network(100, dir = F)
summary(nw ~ edges + offset(triangle))
summary(nw ~ edges + offset(triangle) + gwesp(fixed=F), gw.cutoff = 5)

summary(nw ~ Passthrough(~edges + offset(triangle)))
summary(nw ~ Passthrough(~edges + offset(triangle) + gwesp(fixed=F)), gw.cutoff = 5)
```

produces

```
> require(ergm)
> nw <- network(100, dir = F)
> summary(nw ~ edges + offset(triangle))
           edges offset(triangle) 
              99                1 
> summary(nw ~ edges + offset(triangle) + gwesp(fixed=F), gw.cutoff = 5)
           edges offset(triangle)            esp#1            esp#2            esp#3            esp#4            esp#5 
              99                1                3                0                0                0                0 
> 
> summary(nw ~ Passthrough(~edges + offset(triangle)))
           Passthrough~edges offset(Passthrough~triangle) 
                          99                            1 
> summary(nw ~ Passthrough(~edges + offset(triangle) + gwesp(fixed=F)), gw.cutoff = 5)
   Passthrough~edges Passthrough~triangle    Passthrough~esp#1    Passthrough~esp#2    Passthrough~esp#3    Passthrough~esp#4    Passthrough~esp#5 
                  99                    1                    3                    0                    0                    0                    0 
```

`Passthrough` has dropped the `offset` on `triangle` in the final case.

**Comment by krivit** [comment]
I see. What appears to happen here is that the whole submodel gets "embedded" in a curved term, and the code can't tell that some non-offset theta parameters are mathematically incapable of affecting some eta parameters, so it errs on the side of no offsets. This does, unfortunately, have the effect that they are not properly tagged. (In principle, only *parameters* can be offsets, whereas *statistics* are just numbers, so there is an argument to be made that `summary()` should never have `offset()` decorators.)

However, now is not the time to rethink this.

For now, and since the release is almost ready to go, the stopgap solution is to figure out which curved parameters can mathematically affect which model parameters and propagate offsets accordingly. I.e.,
* Figure it out empirically through `ergm.eta()`. The idea is that we call, e.g.,
    ```r 
    ergm.eta(rep(c(0,NA,0), c(j-1,1,q-j)), etamap)
    ```
    for `j` = 1..`q`, and see which of the elements of `eta` turn NA. The downside is that we may get an error if the map function branches on NA.
* Figure it out empirically through `ergm.etagrad()`, by trying a number of parameter configurations and seeing which cells are nonzero (and here NA and NaN does imply a possible connection). The downside here is that we might miss a configuration where a cell is not 0.

This approach *may* also produce correct but unexpected behaviour. For example, in GW* decay, the decay parameter does not have any effect on the first element of eta, because 
![image](https://user-images.githubusercontent.com/15682462/121828597-69e2cf80-cd03-11eb-9280-961831cc2412.png)
which means that if the θ₁ is an offset but θ₂ is not, then η₁ is an offset but η₂, η₃, ... are not.

I'll test these out in a branch and push out what works reasonably well.
