### ISSUE TITLE
Deprecate ergm.robmon()?

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#385]
As far as I can tell, `ergm.stocapprox()` implements the same algorithm but in C. Is there a reason to keep `ergm.robmon()` around?

**Comment by krivit** [comment]
Also related to https://github.com/statnet/ergm/issues/335. @handcock , @CarterButts , @drh20drh20 ?

**Comment by CarterButts** [comment]
OK, for some reason my reply didn't get added to the issue.  Here was my initial response:

Hmm.  RM is a kind of SA, but historically the two implementations did not seem to be the same*.  Right now SA is sort of working (but a lot of options seem not to be working correctly), and RM is broken, which also would seem to imply that something is different.  RM being broken is unfortunate, because we have needed to use RM for some applications for which GT is too unstable, or too prone to getting stuck. 

All that said, I've not gone through that code, so I'm not entirely clear on what, precisely, the differences were.  There are a zillion ways to implement those methods, and the fine details can matter, so there could be subtleties; or maybe there were just different defaults.  Anyway, I would compare results to verify that there really were differences, but as noted, that's not possible with the current tools.  It might be possible to downgrade ERGM and run a comparison (though you've been going through the code, and that ought to be definitive, in principle).

(* Our most extensive evaluation was done through the graduate student interface, so it's possible that the student's apparently different results were due to an error.  I didn't run those comparisons myself, so caveat and all that.  But it certainly seemed that we got much better results from the default RM implementation than the default SA, from the results that I was shown at the time.)

**Comment by CarterButts** [comment]
Now, a follow-up on that.  I was able to downgrade ergm to 3.11, and run some comparisons with a toy model:

```
library(ergm)
data(emon)
reps<-25
seed<-1331
fitsRM<-vector(mode="list",length=reps)
fitsSA<-vector(mode="list",length=reps)
for(i in 1:reps){
  fitsRM[[i]] <- ergm(emon[[5]] ~ edges + mutual + nodematch("Location") + nodefactor("Sponsorship") + nodematch("Sponsorship") + gwesp(0.25,fixed=TRUE), control=control.ergm(main.method="Robbins"))
  fitsSA[[i]] <- ergm(emon[[5]] ~ edges + mutual + nodematch("Location") + nodefactor("Sponsorship") + nodematch("Sponsorship") + gwesp(0.25,fixed=TRUE), control=control.ergm(main.method="Stochastic"))
}
boxplot(cbind(RM=sapply(fitsRM,AIC),SA=sapply(fitsSA,AIC)),ylab="AIC")
par(mar=c(14,4,2,2))
boxplot(cbind(RM=t(sapply(fitsRM,coef)),SA=t(sapply(fitsSA,coef))),ylab="Coef", las=3, col=rep(c(2,4),each=9))
legend("topright",fill=c(2,4),legend=c("RM","SA"))
```
The output looks like so.  Here are the AIC results:

![image](https://user-images.githubusercontent.com/1232280/135213628-ee39dd50-bf97-410b-91be-11f292aa4ea9.png)

and here are the coefficients:

![image](https://user-images.githubusercontent.com/1232280/135213559-1a74c9cb-421e-4aa9-801b-04d5af4411c3.png)

Interestingly, these results are the opposite of what we were getting in our experiments (SA is far more stable), but (1) I don't recall the ERGM version, and (2) we would have been using very different settings.  At any rate, this does imply that the two implementations were doing something different.

Going forward, it may or may not be worth keeping both.  But it would be good to know what they were doing that was different before scrapping one of them.  It might also be worth considering whether there is any reason to worry about e.g. comparability with either PNet or with older RM implementations for validation or whatnot.  Possibly not (and I presume that PNet has by now evolved its own complex set of tricks that we weren't using), but it seems worth raising the question.

I've attached those model fit objects, in case anyone wants to look at them more closely without downgrading their packages - one needs to downgrade `ergm`, `statnet.common`, and `network` to go back to the pre-4.0 toolchain.  I will need to switch back to the current versions, but hopefully this at least provides some useful information!

[RM_vs_SA_example_fits_ergm_3_11.Rdata.gz](https://github.com/statnet/ergm/files/7249351/RM_vs_SA_example_fits_ergm_3_11.Rdata.gz)

**Comment by krivit** [comment]
The fundamental algorithm is the same: simulate to obtain variances of sufficient statistics (and therefore gradients), invert, and use those as gain for the RM/SA updates.

The tuning parameters are interpreted differently. This is because RM has to return to R every time it wants to update theta, whereas SA updates its theta in C. Therefore, RM makes far less frequent updates.

My current preference is to get rid of RM and focus on optimising SA. Ultimately, we can verify how good an estimate is just by simulating from it.

**Comment by CarterButts** [comment]
Are they using the same inertial strategies?  There are various tweaks on the updating rules one can use.  But anyway, you're right that it might be better to have a single SA module that works well than to worry about maintaining two essentially similar versions.  (Could also be possible to get backwards compatibility via argument specification, which would address any concerns about comparisons with old code.)

**Comment by krivit** [comment]
I don't think there are any particular tweaks: both implementations are pretty direct and dumb, which is something we might consider working on.

**Comment by krivit** [comment]
We need to either fix https://github.com/statnet/ergm/issues/335 or deprecate R-M. At this point, I am about to release 4.2, so I'm going to go ahead and make an executive decision to deprecate. R-M is a simple enough algorithm that little is lost by doing it in C.

**Comment by drh20drh20** [comment]
Agreed. Thanks to Pavel and Carter for the thoughtful thread.  Hopefully SA algorithms generally is a topic we'll keep on the to-do list.
